// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNkBy_5xJIwukDhilP6JSs0mtuFsgyrk',
    appId: '1:1041570751309:web:3cf198e96cfb85585d0d04',
    messagingSenderId: '1041570751309',
    projectId: 'pasante-app',
    authDomain: 'pasante-app.firebaseapp.com',
    storageBucket: 'pasante-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCA1cZog8D_2UVc1FzW8es3yO4JhNudow',
    appId: '1:1041570751309:android:f3566938f3c7f42a5d0d04',
    messagingSenderId: '1041570751309',
    projectId: 'pasante-app',
    storageBucket: 'pasante-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dJSgvZppQ1UdrEBEUE4OeqtwzafaT24',
    appId: '1:1041570751309:ios:d9579b089e96c4c75d0d04',
    messagingSenderId: '1041570751309',
    projectId: 'pasante-app',
    storageBucket: 'pasante-app.appspot.com',
    iosClientId: '1041570751309-qq8vflombd2tj8ef5n84m9s2mll2tn7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasanteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dJSgvZppQ1UdrEBEUE4OeqtwzafaT24',
    appId: '1:1041570751309:ios:d9579b089e96c4c75d0d04',
    messagingSenderId: '1041570751309',
    projectId: 'pasante-app',
    storageBucket: 'pasante-app.appspot.com',
    iosClientId: '1041570751309-qq8vflombd2tj8ef5n84m9s2mll2tn7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasanteApp',
  );
}
